# Generated by Django 4.1 on 2024-10-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('original_title', models.CharField(blank=True, max_length=255, null=True)),
                ('release_date', models.DateField()),
                ('overview', models.TextField(blank=True, null=True)),
                ('original_language', models.CharField(max_length=10)),
                ('language', models.CharField(max_length=50)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('budget', models.BigIntegerField(blank=True, null=True)),
                ('revenue', models.BigIntegerField(blank=True, null=True)),
                ('vote_average', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('vote_count', models.IntegerField(blank=True, null=True)),
                ('homepage', models.URLField(blank=True, null=True)),
                ('production_company_id', models.IntegerField(blank=True, null=True)),
                ('genre_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['release_date'],
            },
        ),
    ]
