# Generated by Django 4.1 on 2024-10-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_viewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
