# Generated by Django 4.1 on 2024-10-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_viewer', '0002_alter_movie_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='budget',
            field=models.BigIntegerField(default=-1),
        ),
    ]
